# Pandas_live class task_30.07

In [23]:
import pandas as pd
agent_performance=pd.read_csv('AgentPerformance (1).xlsx - Agent Performance Report.csv')
agent_login=pd.read_csv('Agent_Login_Report (4).xls - Agent Login Report.csv')

In [37]:
#1 .Find out there avarage rating on weekly basis keep this in a mind that they take two days of leave
agent_performance['week']=agent_performance.Date.dt.week

C:\Users\subho\AppData\Local\Temp\ipykernel_14020\1578778685.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  agent_performance['week']=agent_performance.Date.dt.week

In [59]:
agent_performance.drop(agent_performance[agent_performance['Total Feedback']==0].index,axis=0,inplace=True) #to take care of weekly offs and 0 feedback counts

In [66]:
agent_performance.groupby('week')['Average Rating'].mean()
#remember missing agents did not work for a full week

week
1     4.306667
6     4.391875
10    4.245625
14    4.388750
18    3.795600
23    4.364545
27    3.965357
28    4.349449
29    4.377816
30    4.314259
31    4.344483
36    4.559200
40    4.337000
45    4.431071
49    4.159600
Name: Average Rating, dtype: float64

In [81]:
#2 .Total working days for each agents
agent_performance.groupby('Agent Name').count()['Date']

Agent Name
Aditya Shinde             12
Aditya_iot                17
Ameya Jain                15
Anirudh                    6
Ankitjha                   2
Anurag Tiwari              2
Aravind                   14
Ashad Nasim                2
Ayushi Mishra             24
Bharath                   19
Boktiar Ahmed Bappy       25
Chaitra K Hiremath         6
Deepranjan Gupta          20
Harikrishnan Shaji        19
Hrisikesh Neogi           21
Ishawant Kumar            24
Jawala Prakash            25
Jayant Kumar               8
Jaydeep Dixit             21
Khushboo Priya            25
Madhulika G               24
Mahak                      1
Mahesh Sarade             18
Maitry                    20
Maneesh                    2
Manjunatha A              24
Mithun S                  18
Mukesh                     2
Mukesh Rao                 3
Muskan Garg                5
Nandani Gupta             21
Nishtha Jain              23
Prabir Kumar Satapathy    17
Prateek _iot              16
Prerna Singh              22
Rishav Dash               20
Saikumarreddy N           13
Sandipan Saha              3
Sanjeev Kumar             23
Saurabh Shukla             4
Shiva Srivastava           7
Shivan K                  20
Shivan_S                   1
Shivananda Sonwane        28
Shubham Sharma            21
Sowmiya Sivakumar          9
Sudhanshu Kumar            2
Suraj S Bilgi              2
Swati                     17
Tarun                      1
Vivek                      5
Wasim                     16
Zeeshan                   16
Name: Date, dtype: int64

In [85]:
#3. Total query that you hvae taken
agent_performance.groupby('Agent Name').sum('Total Chats')['Total Chats']

Agent Name
Aditya Shinde             277
Aditya_iot                231
Ameya Jain                322
Anirudh                    80
Ankitjha                    4
Anurag Tiwari               4
Aravind                   366
Ashad Nasim                18
Ayushi Mishra             514
Bharath                   369
Boktiar Ahmed Bappy       450
Chaitra K Hiremath         64
Deepranjan Gupta          492
Harikrishnan Shaji        381
Hrisikesh Neogi           578
Ishawant Kumar            338
Jawala Prakash            439
Jayant Kumar              127
Jaydeep Dixit             512
Khushboo Priya            444
Madhulika G               469
Mahak                       7
Mahesh Sarade             364
Maitry                    542
Maneesh                     3
Manjunatha A              411
Mithun S                  503
Mukesh                     19
Mukesh Rao                  5
Muskan Garg                56
Nandani Gupta             560
Nishtha Jain              373
Prabir Kumar Satapathy    299
Prateek _iot              189
Prerna Singh              401
Rishav Dash               407
Saikumarreddy N           364
Sandipan Saha              30
Sanjeev Kumar             507
Saurabh Shukla             16
Shiva Srivastava           53
Shivan K                  355
Shivan_S                    7
Shivananda Sonwane        441
Shubham Sharma            510
Sowmiya Sivakumar         206
Sudhanshu Kumar             2
Suraj S Bilgi              28
Swati                     524
Tarun                      22
Vivek                      44
Wasim                     433
Zeeshan                   542
Name: Total Chats, dtype: int64

In [87]:
#4. total Feedback that you have received 
agent_performance.groupby('Agent Name').sum('Total Feedback')['Total Feedback']

Agent Name
Aditya Shinde             153
Aditya_iot                131
Ameya Jain                228
Anirudh                    39
Ankitjha                    3
Anurag Tiwari               3
Aravind                   233
Ashad Nasim                 9
Ayushi Mishra             329
Bharath                   247
Boktiar Ahmed Bappy       311
Chaitra K Hiremath         37
Deepranjan Gupta          312
Harikrishnan Shaji        231
Hrisikesh Neogi           367
Ishawant Kumar            202
Jawala Prakash            250
Jayant Kumar               70
Jaydeep Dixit             305
Khushboo Priya            289
Madhulika G               281
Mahak                       5
Mahesh Sarade             216
Maitry                    347
Maneesh                     3
Manjunatha A              254
Mithun S                  364
Mukesh                     17
Mukesh Rao                  5
Muskan Garg                37
Nandani Gupta             308
Nishtha Jain              257
Prabir Kumar Satapathy    222
Prateek _iot              107
Prerna Singh              235
Rishav Dash               264
Saikumarreddy N           290
Sandipan Saha              18
Sanjeev Kumar             311
Saurabh Shukla              8
Shiva Srivastava           46
Shivan K                  243
Shivan_S                    4
Shivananda Sonwane        263
Shubham Sharma            300
Sowmiya Sivakumar         141
Sudhanshu Kumar             2
Suraj S Bilgi              15
Swati                     302
Tarun                       6
Vivek                      20
Wasim                     284
Zeeshan                   335
Name: Total Feedback, dtype: int64

In [123]:
#5. agent name who have average rating between 3.5 to 4
agent_performance[(agent_performance['Average Rating']>=3.5) & (agent_performance['Average Rating']<=4)].groupby('Agent Name').first()['Average Rating']

Agent Name
Aditya Shinde             3.54
Aditya_iot                3.86
Ameya Jain                4.00
Anirudh                   3.77
Anurag Tiwari             3.50
Ashad Nasim               4.00
Ayushi Mishra             3.88
Boktiar Ahmed Bappy       4.00
Chaitra K Hiremath        4.00
Deepranjan Gupta          3.69
Harikrishnan Shaji        3.73
Hrisikesh Neogi           3.77
Ishawant Kumar            3.75
Jawala Prakash            3.89
Jayant Kumar              3.76
Jaydeep Dixit             3.95
Khushboo Priya            3.79
Madhulika G               3.62
Mahesh Sarade             3.94
Maitry                    4.00
Maneesh                   4.00
Manjunatha A              3.60
Mithun S                  3.75
Muskan Garg               4.00
Nandani Gupta             3.79
Nishtha Jain              3.67
Prabir Kumar Satapathy    4.00
Prateek _iot              3.75
Prerna Singh              3.80
Rishav Dash               3.80
Sandipan Saha             3.62
Sanjeev Kumar             4.00
Saurabh Shukla            3.67
Shiva Srivastava          4.00
Shivan K                  4.00
Shivananda Sonwane        3.53
Shubham Sharma            4.00
Swati                     3.67
Wasim                     3.95
Zeeshan                   3.79
Name: Average Rating, dtype: float64

In [95]:
#6 . Agent name who have rating lesss then 3.5
agent_performance[agent_performance['Average Rating']<3.5].groupby('Agent Name').first()['Average Rating']

Agent Name
Aditya_iot             2.67
Anirudh                1.00
Ankitjha               3.00
Anurag Tiwari          2.00
Ashad Nasim            1.00
Ayushi Mishra          3.25
Boktiar Ahmed Bappy    2.71
Chaitra K Hiremath     3.43
Harikrishnan Shaji     3.25
Ishawant Kumar         3.18
Jawala Prakash         3.00
Jayant Kumar           3.17
Mahak                  3.00
Mahesh Sarade          2.75
Maneesh                1.00
Mithun S               3.29
Mukesh Rao             1.00
Nandani Gupta          3.14
Nishtha Jain           3.36
Prerna Singh           3.33
Sanjeev Kumar          3.00
Saurabh Shukla         3.00
Shiva Srivastava       2.17
Shivan K               1.00
Shivananda Sonwane     3.40
Sowmiya Sivakumar      3.43
Tarun                  1.50
Vivek                  1.00
Name: Average Rating, dtype: float64

In [94]:
#7 . agent name who have rating more then 4.5
agent_performance[agent_performance['Average Rating']>4.5].groupby('Agent Name').first()['Average Rating']

Agent Name
Aditya Shinde             4.53
Aditya_iot                4.60
Ameya Jain                4.55
Anirudh                   5.00
Ankitjha                  5.00
Aravind                   4.53
Ayushi Mishra             5.00
Bharath                   4.85
Boktiar Ahmed Bappy       4.75
Chaitra K Hiremath        5.00
Deepranjan Gupta          4.80
Harikrishnan Shaji        4.57
Hrisikesh Neogi           4.80
Ishawant Kumar            4.67
Jawala Prakash            4.83
Jayant Kumar              5.00
Jaydeep Dixit             4.78
Khushboo Priya            4.71
Madhulika G               4.56
Mahesh Sarade             4.71
Maitry                    5.00
Manjunatha A              4.54
Mithun S                  4.80
Mukesh                    4.62
Mukesh Rao                5.00
Muskan Garg               5.00
Nandani Gupta             4.62
Nishtha Jain              5.00
Prabir Kumar Satapathy    4.86
Prateek _iot              4.83
Prerna Singh              4.62
Rishav Dash               4.71
Saikumarreddy N           5.00
Sandipan Saha             5.00
Sanjeev Kumar             5.00
Saurabh Shukla            5.00
Shiva Srivastava          5.00
Shivan K                  4.78
Shivananda Sonwane        5.00
Shubham Sharma            4.67
Sowmiya Sivakumar         4.75
Sudhanshu Kumar           5.00
Suraj S Bilgi             5.00
Swati                     4.53
Vivek                     5.00
Wasim                     4.71
Zeeshan                   4.85
Name: Average Rating, dtype: float64

In [98]:
#8 . how many feedaback agents have received more then 4.5 average
agent_performance[agent_performance['Average Rating']>4.5].groupby('Agent Name').first()['Total Feedback']

Agent Name
Aditya Shinde             15
Aditya_iot                10
Ameya Jain                11
Anirudh                    2
Ankitjha                   1
Aravind                   17
Ayushi Mishra              3
Bharath                   13
Boktiar Ahmed Bappy        4
Chaitra K Hiremath         4
Deepranjan Gupta           5
Harikrishnan Shaji         7
Hrisikesh Neogi           20
Ishawant Kumar             3
Jawala Prakash             6
Jayant Kumar               4
Jaydeep Dixit             18
Khushboo Priya            14
Madhulika G               18
Mahesh Sarade              7
Maitry                     2
Manjunatha A              13
Mithun S                  15
Mukesh                     8
Mukesh Rao                 1
Muskan Garg                4
Nandani Gupta             13
Nishtha Jain               4
Prabir Kumar Satapathy    14
Prateek _iot               6
Prerna Singh              13
Rishav Dash                7
Saikumarreddy N           12
Sandipan Saha              1
Sanjeev Kumar              6
Saurabh Shukla             2
Shiva Srivastava           2
Shivan K                   9
Shivananda Sonwane         1
Shubham Sharma            15
Sowmiya Sivakumar         16
Sudhanshu Kumar            1
Suraj S Bilgi              4
Swati                     15
Vivek                      3
Wasim                     14
Zeeshan                   20
Name: Total Feedback, dtype: int64

In [125]:
#9 . average weekly response time for each agent
agent_performance.groupby('week').first()[['Agent Name','Average Response Time']]
#agent_performance['Average Response Time']=pd.to_datetime(agent_performance['Average Response Time']) to convert Average Response Time to datetime object
#remember missing agents did not work for a full week

            Agent Name Average Response Time
week
1         Manjunatha A   2022-07-30 00:00:54
6          Madhulika G   2022-07-30 00:02:01
10      Jawala Prakash   2022-07-30 00:01:08
14        Nishtha Jain   2022-07-30 00:00:37
18            Anirudh    2022-07-30 00:00:00
23         Madhulika G   2022-07-30 00:01:34
27       Sanjeev Kumar   2022-07-30 00:01:00
28      Ishawant Kumar   2022-07-30 00:01:37
29    Shiva Srivastava   2022-07-30 00:00:47
30        Prerna Singh   2022-07-30 00:00:38
31        Nishtha Jain   2022-07-30 00:01:15
36         Madhulika G   2022-07-30 00:01:29
40      Ishawant Kumar   2022-07-30 00:01:14
45            Anirudh    2022-07-30 00:00:43
49            Anirudh    2022-07-30 00:01:08

In [130]:
#10 . average weekely resolution time for each agents
#agent_performance['Average Resolution Time']=pd.to_datetime(agent_performance['Average Resolution Time'])# converting Average Resolution Time to datetime object
agent_performance.groupby('week').first()[['Agent Name','Average Resolution Time']]
#remember missing agents did not work for a full week

            Agent Name Average Resolution Time
week
1         Manjunatha A     2022-07-30 00:14:52
6          Madhulika G     2022-07-30 00:11:31
10      Jawala Prakash     2022-07-30 00:13:45
14        Nishtha Jain     2022-07-30 00:05:21
18            Anirudh      2022-07-30 00:05:32
23         Madhulika G     2022-07-30 00:13:17
27       Sanjeev Kumar     2022-07-30 00:13:42
28      Ishawant Kumar     2022-07-30 00:11:46
29    Shiva Srivastava     2022-07-30 00:04:18
30        Prerna Singh     2022-07-30 00:04:20
31        Nishtha Jain     2022-07-30 00:23:21
36         Madhulika G     2022-07-30 00:21:53
40      Ishawant Kumar     2022-07-30 00:22:34
45            Anirudh      2022-07-30 00:13:19
49            Anirudh      2022-07-30 00:22:30

In [136]:
#11 . list of all agents name
agent_performance.groupby('Agent Name').first().index

Index(['Aditya Shinde', 'Aditya_iot ', 'Ameya Jain', 'Anirudh ', 'Ankitjha ',
       'Anurag Tiwari', 'Aravind ', 'Ashad Nasim', 'Ayushi Mishra', 'Bharath ',
       'Boktiar Ahmed Bappy', 'Chaitra K Hiremath', 'Deepranjan Gupta',
       'Harikrishnan Shaji', 'Hrisikesh Neogi', 'Ishawant Kumar',
       'Jawala Prakash', 'Jayant Kumar', 'Jaydeep Dixit', 'Khushboo Priya',
       'Madhulika G', 'Mahak ', 'Mahesh Sarade', 'Maitry ', 'Maneesh ',
       'Manjunatha A', 'Mithun S', 'Mukesh ', 'Mukesh Rao ', 'Muskan Garg',
       'Nandani Gupta', 'Nishtha Jain', 'Prabir Kumar Satapathy',
       'Prateek _iot ', 'Prerna Singh', 'Rishav Dash', 'Saikumarreddy N',
       'Sandipan Saha', 'Sanjeev Kumar', 'Saurabh Shukla', 'Shiva Srivastava',
       'Shivan K', 'Shivan_S ', 'Shivananda Sonwane', 'Shubham Sharma',
       'Sowmiya Sivakumar', 'Sudhanshu Kumar', 'Suraj S Bilgi', 'Swati ',
       'Tarun ', 'Vivek ', 'Wasim ', 'Zeeshan '],
      dtype='object', name='Agent Name')

In [144]:
#12. percentage of chat on which they have received a feedback 
a=agent_performance.groupby('Agent Name').sum('Total Chats')
a['feedback %']=a['Total Feedback']/a['Total Chats']*100
a['feedback %']

Agent Name
Aditya Shinde              55.234657
Aditya_iot                 56.709957
Ameya Jain                 70.807453
Anirudh                    48.750000
Ankitjha                   75.000000
Anurag Tiwari              75.000000
Aravind                    63.661202
Ashad Nasim                50.000000
Ayushi Mishra              64.007782
Bharath                    66.937669
Boktiar Ahmed Bappy        69.111111
Chaitra K Hiremath         57.812500
Deepranjan Gupta           63.414634
Harikrishnan Shaji         60.629921
Hrisikesh Neogi            63.494810
Ishawant Kumar             59.763314
Jawala Prakash             56.947608
Jayant Kumar               55.118110
Jaydeep Dixit              59.570312
Khushboo Priya             65.090090
Madhulika G                59.914712
Mahak                      71.428571
Mahesh Sarade              59.340659
Maitry                     64.022140
Maneesh                   100.000000
Manjunatha A               61.800487
Mithun S                   72.365805
Mukesh                     89.473684
Mukesh Rao                100.000000
Muskan Garg                66.071429
Nandani Gupta              55.000000
Nishtha Jain               68.900804
Prabir Kumar Satapathy     74.247492
Prateek _iot               56.613757
Prerna Singh               58.603491
Rishav Dash                64.864865
Saikumarreddy N            79.670330
Sandipan Saha              60.000000
Sanjeev Kumar              61.341223
Saurabh Shukla             50.000000
Shiva Srivastava           86.792453
Shivan K                   68.450704
Shivan_S                   57.142857
Shivananda Sonwane         59.637188
Shubham Sharma             58.823529
Sowmiya Sivakumar          68.446602
Sudhanshu Kumar           100.000000
Suraj S Bilgi              53.571429
Swati                      57.633588
Tarun                      27.272727
Vivek                      45.454545
Wasim                      65.588915
Zeeshan                    61.808118
Name: feedback %, dtype: float64

In [147]:
#13 . Total contributation hour for each and every agents weekly basis 
#agent_login['week']=agent_login['Date'].dt.week to add a week column in the data frame

C:\Users\subho\AppData\Local\Temp\ipykernel_14020\1744441433.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  agent_login['week']=agent_login['Date'].dt.week

In [227]:
agent_login['dt_duration']=agent_login['Duration'].apply(lambda x :int(x[:2])*3600+int(x[3:5])*60+int(x[6:]))
#agent_login['dt_duration']=pd.to_datetime(agent_login['dt_duration'],unit='s')
#had to do some work around as could not convert the 'Duration' column into date time straightaway
b=agent_login.groupby('Agent').sum('dt_duration')
b['dt_duration']=pd.to_datetime(b['dt_duration'],unit='s')
b['dt_duration']# couldn't care to remove '1970-01-01'
#remember all agents did not work for a full week

Agent
Aditya Shinde            1970-01-01 00:02:10
Aditya_iot               1970-01-01 15:43:52
Amersh                   1970-01-01 03:03:50
Ameya Jain               1970-01-02 18:04:32
Ankitjha                 1970-01-01 02:16:01
Anurag Tiwari            1970-01-01 02:46:44
Aravind                  1970-01-02 00:17:57
Ayushi Mishra            1970-01-02 14:07:18
Bharath                  1970-01-03 00:04:36
Boktiar Ahmed Bappy      1970-01-02 16:16:07
Chaitra K Hiremath       1970-01-02 10:19:32
Deepranjan Gupta         1970-01-05 10:16:31
Dibyanshu                1970-01-03 04:35:45
Harikrishnan Shaji       1970-01-03 05:42:53
Hrisikesh Neogi          1970-01-03 09:34:07
Hyder Abbas              1970-01-01 00:23:17
Ineuron Intelligence     1970-01-01 01:26:55
Ishawant Kumar           1970-01-03 03:46:44
Jawala Prakash           1970-01-02 22:24:08
Jaydeep Dixit            1970-01-03 11:50:26
Khushboo Priya           1970-01-02 19:33:31
Madhulika G              1970-01-02 22:03:37
Mahesh Sarade            1970-01-02 18:55:19
Maitry                   1970-01-02 06:56:42
Manjunatha A             1970-01-02 17:16:29
Mithun S                 1970-01-02 21:10:25
Mukesh                   1970-01-01 08:54:18
Muskan Garg              1970-01-01 17:20:08
Nandani Gupta            1970-01-02 16:10:20
Nishtha Jain             1970-01-02 19:51:10
Nitin M                  1970-01-01 00:47:56
Prabir Kumar Satapathy   1970-01-02 09:22:38
Prateek _iot             1970-01-01 18:25:05
Prerna Singh             1970-01-02 21:42:56
Rishav Dash              1970-01-02 17:46:32
Saikumarreddy N          1970-01-02 19:08:15
Sanjeev Kumar            1970-01-02 20:41:14
Saurabh Shukla           1970-01-01 16:39:47
Shiva Srivastava         1970-01-01 14:59:39
Shivan K                 1970-01-02 12:06:08
Shivananda Sonwane       1970-01-03 01:17:16
Shubham Sharma           1970-01-03 05:47:54
Sowmiya Sivakumar        1970-01-02 20:45:15
Sudhanshu Kumar          1970-01-02 22:13:52
Suraj S Bilgi            1970-01-01 12:33:33
Swati                    1970-01-02 01:00:04
Wasim                    1970-01-03 00:10:45
Zeeshan                  1970-01-03 01:05:19
Name: dt_duration, dtype: datetime64[ns]

In [233]:
#14. total percentage of active hour for a month
agent_login['month']=agent_login['Date'].dt.month
c=agent_login.groupby('Agent').first()
c['active hour %']=c['dt_duration']*100/8*3600
c

,SL No,Date,Login Time,Logout Time,Duration,week,dt_duration,month,active hour %
Agent,,,,,,,,,
Aditya Shinde,403,2022-07-26,2022-07-30 20:17:35,2022-07-30 20:19:45,00:02:10,30,130,7,5.850000e+06
Aditya_iot,73,2022-07-29,2022-07-30 17:51:57,2022-07-30 20:04:03,02:12:05,30,7925,7,3.566250e+08
Amersh,217,2022-07-28,2022-07-30 11:49:46,2022-07-30 11:52:26,00:02:40,30,160,7,7.200000e+06
Ameya Jain,202,2022-07-28,2022-07-30 15:00:47,2022-07-30 21:00:31,05:59:44,30,21584,7,9.712800e+08
Ankitjha,332,2022-07-27,2022-07-30 13:46:08,2022-07-30 15:47:32,02:01:24,30,7284,7,3.277800e+08
Anurag Tiwari,11,2022-07-30,2022-07-30 13:06:12,2022-07-30 13:11:57,00:05:44,30,344,7,1.548000e+07
Aravind,210,2022-07-28,2022-07-30 13:53:02,2022-07-30 13:54:11,00:01:09,30,69,7,3.105000e+06
Ayushi Mishra,55,2022-07-29,2022-07-30 20:40:28,2022-07-30 20:46:50,00:06:21,30,381,7,1.714500e+07
Bharath,132,2022-07-29,2022-07-30 08:55:47,2022-07-30 14:59:16,06:03:29,30,21809,7,9.814050e+08
Boktiar Ahmed Bappy,34,2022-07-30,2022-07-30 02:09:33,2022-07-30 02:52:03,00:42:29,30,2549,7,1.147050e+08
Chaitra K Hiremath,59,2022-07-29,2022-07-30 19:41:48,2022-07-30 19:43:58,00:02:10,30,130,7,5.850000e+06
Deepranjan Gupta,49,2022-07-29,2022-07-30 21:02:24,2022-07-30 03:07:02,06:04:37,30,21877,7,9.844650e+08
Dibyanshu,36,2022-07-29,2022-07-30 23:29:51,2022-07-30 00:37:20,01:07:28,30,4048,7,1.821600e+08
Harikrishnan Shaji,8,2022-07-30,2022-07-30 13:53:05,2022-07-30 16:06:49,02:13:43,30,8023,7,3.610350e+08
Hrisikesh Neogi,4,2022-07-30,2022-07-30 14:34:29,2022-07-30 15:19:35,00:45:06,30,2706,7,1.217700e+08
Hyder Abbas,482,2022-07-25,2022-07-30 22:18:57,2022-07-30 22:22:05,00:03:07,30,187,7,8.415000e+06
Ineuron Intelligence,987,2022-07-20,2022-07-30 12:50:54,2022-07-30 14:17:50,01:26:55,29,5215,7,2.346750e+08
Ishawant Kumar,12,2022-07-30,2022-07-30 13:05:35,2022-07-30 13:12:45,00:07:10,30,430,7,1.935000e+07
Jawala Prakash,35,2022-07-29,2022-07-30 23:40:40,2022-07-30 03:06:43,03:26:03,30,12363,7,5.563350e+08
Jaydeep Dixit,51,2022-07-29,2022-07-30 20:57:35,2022-07-30 21:02:05,00:04:30,30,270,7,1.215000e+07
Khushboo Priya,2,2022-07-30,2022-07-30 15:06:59,2022-07-30 15:07:16,00:00:17,30,17,7,7.650000e+05
Madhulika G,33,2022-07-30,2022-07-30 08:58:44,2022-07-30 14:19:14,05:20:30,30,19230,7,8.653500e+08
Mahesh Sarade,56,2022-07-29,2022-07-30 20:08:50,2022-07-30 21:08:35,00:59:45,30,3585,7,1.613250e+08
Maitry,401,2022-07-26,2022-07-30 20:45:03,2022-07-30 03:02:18,06:17:14,30,22634,7,1.018530e+09
Manjunatha A,7,2022-07-30,2022-07-30 14:00:12,2022-07-30 15:08:29,01:08:16,30,4096,7,1.843200e+08
Mithun S,28,2022-07-30,2022-07-30 09:13:18,2022-07-30 15:14:28,06:01:10,30,21670,7,9.751500e+08
Mukesh,5,2022-07-30,2022-07-30 14:03:15,2022-07-30 15:11:52,01:08:36,30,4116,7,1.852200e+08
Muskan Garg,57,2022-07-29,2022-07-30 19:48:19,2022-07-30 22:06:25,02:18:06,30,8286,7,3.728700e+08
Nandani Gupta,3,2022-07-30,2022-07-30 15:04:24,2022-07-30 17:31:07,02:26:42,30,8802,7,3.960900e+08
Nishtha Jain,21,2022-07-30,2022-07-30 11:34:54,2022-07-30 15:06:11,03:31:17,30,12677,7,5.704650e+08
Nitin M,765,2022-07-22,2022-07-30 13:01:55,2022-07-30 13:49:51,00:47:56,29,2876,7,1.294200e+08
Prabir Kumar Satapathy,83,2022-07-29,2022-07-30 15:44:14,2022-07-30 15:55:24,00:11:10,30,670,7,3.015000e+07
Prateek _iot,22,2022-07-30,2022-07-30 11:16:36,2022-07-30 11:20:26,00:03:50,30,230,7,1.035000e+07
Prerna Singh,16,2022-07-30,2022-07-30 12:32:28,2022-07-30 14:10:08,01:37:40,30,5860,7,2.637000e+08
Rishav Dash,129,2022-07-29,2022-07-30 09:03:17,2022-07-30 15:42:45,06:39:27,30,23967,7,1.078515e+09
Saikumarreddy N,203,2022-07-28,2022-07-30 14:59:08,2022-07-30 21:00:39,06:01:31,30,21691,7,9.760950e+08
Sanjeev Kumar,94,2022-07-29,2022-07-30 14:59:58,2022-07-30 21:05:44,06:05:46,30,21946,7,9.875700e+08
Saurabh Shukla,696,2022-07-23,2022-07-30 08:35:20,2022-07-30 09:18:20,00:43:00,29,2580,7,1.161000e+08
Shiva Srivastava,62,2022-07-29,2022-07-30 19:32:34,2022-07-30 22:03:09,02:30:34,30,9034,7,4.065300e+08
Shivan K,10,2022-07-30,2022-07-30 13:28:18,2022-07-30 13:59:00,00:30:42,30,1842,7,8.289000e+07
Shivananda Sonwane,1,2022-07-30,2022-07-30 15:35:29,2022-07-30 17:39:39,02:04:10,30,7450,7,3.352500e+08
Shubham Sharma,14,2022-07-30,2022-07-30 12:48:50,2022-07-30 13:03:10,00:14:20,30,860,7,3.870000e+07
Sowmiya Sivakumar,6,2022-07-30,2022-07-30 14:03:11,2022-07-30 15:05:37,01:02:26,30,3746,7,1.685700e+08
Sudhanshu Kumar,317,2022-07-27,2022-07-30 15:26:06,2022-07-30 16:26:39,01:00:33,30,3633,7,1.634850e+08
Suraj S Bilgi,9,2022-07-30,2022-07-30 13:50:01,2022-07-30 15:11:42,01:21:41,30,4901,7,2.205450e+08
Swati,515,2022-07-25,2022-07-30 15:01:01,2022-07-30 21:09:34,06:08:33,30,22113,7,9.950850e+08
Wasim,131,2022-07-29,2022-07-30 09:00:07,2022-07-30 16:19:57,07:19:50,30,26390,7,1.187550e+09
Zeeshan,97,2022-07-29,2022-07-30 14:52:37,2022-07-30 21:05:28,06:12:50,30,22370,7,1.006650e+09